import type { Question } from '../types/game';

export const QUESTIONS: Question[] = [
  // ==================== SOAL LAMA (1-32) ====================
  {
    id: 1,
    q: 'Tokoh yang dianggap bapak liberalisme klasik dengan gagasan hak alami (life, liberty, property)?',
    opts: ['John Locke', 'Karl Marx', 'Adam Smith', 'Benito Mussolini'],
    correct: 0,
    why: 'John Locke mengembangkan gagasan hak alami manusia yang menjadi fondasi dasar liberalisme.',
  },
  {
    id: 2,
    q: 'Revolusi yang menjadi tonggak lahirnya nilai-nilai liberalisme modern di Eropa?',
    opts: ['Revolusi Industri', 'Revolusi Prancis 1789', 'Revolusi Rusia 1917', 'Revolusi Amerika 1776 saja'],
    correct: 1,
    why: 'Revolusi Prancis 1789 mempopulerkan gagasan kebebasan (liberté), persamaan (égalité), dan persaudaraan.',
  },
  {
    id: 3,
    q: 'Liberalisme secara politik paling menekankan pada?',
    opts: ['Kekuasaan mutlak negara', 'Kebebasan dan hak individu', 'Kepemilikan kolektif', 'Superioritas ras'],
    correct: 1,
    why: 'Liberalisme menjunjung tinggi kebebasan dan hak-hak asasi individu di atas otoritas negara.',
  },
  {
    id: 4,
    q: 'Sistem pemerintahan yang umumnya didorong oleh paham liberalisme?',
    opts: ['Demokrasi konstitusional', 'Diktator militer', 'Monarki absolut', 'Negara satu partai'],
    correct: 0,
    why: 'Liberalisme mendorong demokrasi dengan aturan konstitusi yang membatasi kesewenang-wenangan penguasa.',
  },
  {
    id: 5,
    q: 'Karl Marx dan Friedrich Engels menulis dokumen penting tahun 1848 yang berjudul?',
    opts: ['The Wealth of Nations', 'Manifesto Komunis', 'Mein Kampf', 'The Social Contract'],
    correct: 1,
    why: 'Manifesto Komunis (1848) berisi seruan dan analisis perjuangan kelas antara kaum borjuis dan proletar.',
  },
  {
    id: 6,
    q: 'Konsep sentral Marx tentang konflik antara pemilik modal dan buruh disebut?',
    opts: ['Perang saudara', 'Pertentangan kelas', 'Revolusi hijau', 'Kontrak sosial'],
    correct: 1,
    why: 'Marx memandang sejarah peradaban digerakkan oleh pertentangan kelas ekonomi.',
  },
  {
    id: 7,
    q: 'Negara pertama yang menerapkan komunisme setelah Revolusi 1917 adalah?',
    opts: ['China', 'Kuba', 'Uni Soviet (Rusia)', 'Vietnam'],
    correct: 2,
    why: 'Revolusi Bolshevik Oktober 1917 melahirkan Uni Soviet sebagai negara sosialis/komunis pertama di dunia.',
  },
  {
    id: 8,
    q: 'Tokoh yang memimpin Revolusi Bolshevik 1917 di Rusia?',
    opts: ['Joseph Stalin', 'Vladimir Lenin', 'Leon Trotsky saja', 'Nikita Khrushchev'],
    correct: 1,
    why: 'Vladimir Lenin memimpin faksi Bolshevik merebut kekuasaan dan mendirikan pemerintahan Soviet.',
  },
  {
    id: 9,
    q: 'Ciri utama ekonomi komunis adalah kepemilikan alat produksi berada di tangan?',
    opts: ['Individu/swasta', 'Negara atau kolektif', 'Perusahaan multinasional', 'Gereja / agamawan'],
    correct: 1,
    why: 'Dalam komunisme, alat produksi dikuasai secara kolektif oleh negara untuk kesejahteraan bersama tanpa kelas.',
  },
  {
    id: 10,
    q: 'Fasisme modern pertama kali berkembang dan berkuasa di negara?',
    opts: ['Jerman', 'Spanyol', 'Italia', 'Jepang'],
    correct: 2,
    why: 'Fasisme lahir di Italia pada 1920-an di bawah kepemimpinan Benito Mussolini.',
  },
  {
    id: 11,
    q: 'Tokoh yang memimpin gerakan fasisme di Italia?',
    opts: ['Francisco Franco', 'Benito Mussolini', 'Adolf Hitler', 'Hirohito'],
    correct: 1,
    why: 'Benito Mussolini adalah pencetus istilah fasisme (fascio) dan penguasa fasis Italia.',
  },
  {
    id: 12,
    q: 'Bentuk fasisme yang berkembang di Jerman di bawah Adolf Hitler disebut?',
    opts: ['Leninisme', 'Nazisme (Nasional-Sosialisme)', 'Maoisme', 'Anarko-sindikalisme'],
    correct: 1,
    why: 'Nazisme adalah varian fasisme Jerman yang menambahkan doktrin rasisme biologis ke dalam ultranasionalisme.',
  },
  {
    id: 13,
    q: 'Ciri fasisme yang menonjolkan superioritas bangsa/negara di atas individu disebut?',
    opts: ['Ultranasionalisme', 'Internasionalisme', 'Federalisme', 'Egalitarianisme'],
    correct: 0,
    why: 'Fasisme menempatkan kepentingan dan kejayaan bangsa/negara di atas segala kebebasan individu.',
  },
  {
    id: 14,
    q: 'Fasisme umumnya menolak keras sistem pemerintahan berupa?',
    opts: ['Monarki', 'Demokrasi liberal/parlementer', 'Kediktatoran', 'Militerisme'],
    correct: 1,
    why: 'Fasisme menganggap demokrasi liberal lemah dan memecah belah persatuan nasional.',
  },
  {
    id: 15,
    q: "Tokoh yang menulis 'The Wealth of Nations' (1776) dan dianggap bapak ekonomi kapitalisme?",
    opts: ['Adam Smith', 'John Maynard Keynes', 'David Ricardo', 'Thomas Malthus'],
    correct: 0,
    why: "Adam Smith meletakkan dasar ekonomi pasar bebas lewat bukunya 'The Wealth of Nations'.",
  },
  {
    id: 16,
    q: "Konsep 'tangan tak terlihat' (invisible hand) dalam kapitalisme dikemukakan oleh?",
    opts: ['Karl Marx', 'Adam Smith', 'Vladimir Lenin', 'Benito Mussolini'],
    correct: 1,
    why: "Adam Smith mengemukakan bahwa mekanisme pasar bekerja secara alami mengatur pasokan dan harga bagai 'tangan tak terlihat'.",
  },
  {
    id: 17,
    q: 'Dalam kapitalisme, alat produksi umumnya dimiliki oleh?',
    opts: ['Negara secara mutlak', 'Swasta / individu', 'Komite militer', 'Partai tunggal'],
    correct: 1,
    why: 'Kapitalisme bertumpu pada hak milik pribadi dan inisiatif usaha swasta untuk mencari profit.',
  },
  {
    id: 18,
    q: 'Peristiwa sejarah abad 18-19 yang mempercepat berkembangnya kapitalisme industri di Eropa?',
    opts: ['Revolusi Industri', 'Revolusi Hijau', 'Revolusi Prancis', 'Revolusi Rusia'],
    correct: 0,
    why: 'Revolusi Industri di Inggris mendorong otomatisasi pabrik, akumulasi modal, dan sistem upah modern.',
  },
  {
    id: 19,
    q: 'Negara adidaya yang menjadi simbol utama kapitalisme dan ekonomi pasar bebas di abad ke-20?',
    opts: ['Kuba', 'Amerika Serikat', 'Korea Utara', 'Uni Soviet'],
    correct: 1,
    why: 'Amerika Serikat menjadi poros utama ekonomi kapitalis dunia terutama sepanjang era pasca Perang Dunia II.',
  },
  {
    id: 20,
    q: 'Ideologi mana yang paling menentang kepemilikan pribadi atas alat produksi pabrik dan tanah?',
    opts: ['Liberalisme', 'Kapitalisme', 'Komunisme', 'Konservatisme'],
    correct: 2,
    why: 'Komunisme memandang kepemilikan pribadi atas alat produksi sebagai sumber utama eksploitasi manusia.',
  },
  {
    id: 21,
    q: 'Ideologi mana yang paling menekankan kultus individu pemimpin, militerisme, dan ekspansi wilayah?',
    opts: ['Liberalisme', 'Fasisme', 'Kapitalisme', 'Sosialisme Demokratis'],
    correct: 1,
    why: 'Fasisme memuliakan kepatuhan buta pada figur pemimpin agung (Duce/Führer) dan kekuatan militer perang.',
  },
  {
    id: 22,
    q: 'Ideologi mana yang paling menjunjung kebebasan berpendapat, pers bebas, dan pemilu berkala?',
    opts: ['Fasisme', 'Komunisme', 'Liberalisme', 'Totalitarianisme'],
    correct: 2,
    why: 'Pluralisme suara, keterbukaan pers, dan pemilu bebas adalah pilar utama masyarakat liberal.',
  },
  {
    id: 23,
    q: 'Ideologi mana yang memprioritaskan persaingan pasar bebas dengan peran regulasi negara seminimal mungkin?',
    opts: ['Komunisme', 'Kapitalisme', 'Fasisme', 'Merkantilisme'],
    correct: 1,
    why: 'Kapitalisme (laissez-faire) meyakini kompetisi bebas adalah cara paling efisien dalam mengalokasikan sumber daya ekonomi.',
  },
  {
    id: 24,
    q: 'Perang Dingin (Cold War) merupakan rivalitas ideologi global antara blok Barat melawan blok Timur penganut paham?',
    opts: ['Fasisme', 'Komunisme', 'Monarki Teokratis', 'Anarkisme'],
    correct: 1,
    why: 'Perang Dingin (1947–1991) mempertemukan blok Barat (AS-NATO) melawan blok komunis (Uni Soviet-Pakta Warsawa).',
  },
  {
    id: 25,
    q: 'Partai Nazi pimpinan Adolf Hitler di Jerman mulai resmi berkuasa pada tahun?',
    opts: ['1917', '1933', '1939', '1945'],
    correct: 1,
    why: 'Hitler diangkat menjadi Kanselir Jerman pada Januari 1933, menandai dimulainya rezim Reich Ketiga.',
  },
  {
    id: 26,
    q: 'China di bawah kepemimpinan Mao Zedong mempraktikkan ideologi komunisme dengan varian khas yang disebut?',
    opts: ['Kapitalisme Pasar', 'Fasisme Timur', 'Maoisme', 'Liberalisme Asia'],
    correct: 2,
    why: 'Maoisme menempatkan kaum tani desa sebagai ujung tombak revolusi sosialis, berbeda dari model buruh pabrik kota ala Lenin.',
  },
  {
    id: 27,
    q: 'Salah satu kritik paling umum terhadap sistem kapitalisme murni tanpa regulasi adalah?',
    opts: ['Menghapuskan uang dan pasar', 'Memperlebar kesenjangan sosial dan ekonomi', 'Mewujudkan kesetaraan upah mutlak', 'Menghilangkan kepemilikan tanah'],
    correct: 1,
    why: 'Kritik utama kapitalisme adalah kecenderungan akumulasi kekayaan pada segelintir konglomerat dan timbulnya jurang ketimpangan.',
  },
  {
    id: 28,
    q: "Slogan Revolusi Prancis yang menginspirasi gerakan liberalisme adalah 'Liberté, Égalité, ...'?",
    opts: ['Fraternité (Persaudaraan)', 'Propriété', 'Sécurité', 'Autorité'],
    correct: 0,
    why: 'Liberté, Égalité, Fraternité menjadi semboyan abadi Republik Prancis dan perjuangan hak-hak sipil.',
  },
  {
    id: 29,
    q: "Istilah ekonomi 'Laissez-faire' yang sering dikaitkan dengan kapitalisme memiliki arti harfiah?",
    opts: ['Biarkan negara mengatur', 'Biarkan terjadi / jangan campur tangan', 'Bagi rata hasil kerja', 'Perdagangan dengan senjata'],
    correct: 1,
    why: "'Laissez-faire, laissez-passer' berarti biarkan pasar bergerak bebas tanpa intervensi pemerintah.",
  },
  {
    id: 30,
    q: 'Runtuhnya Tembok Berlin pada tahun 1989 menjadi simbol penting dari?',
    opts: ['Kemenangan blok Fasis', 'Runtuhnya pengaruh komunisme di Eropa Timur', 'Awal mula Perang Dingin', 'Berakhirnya sistem demokrasi'],
    correct: 1,
    why: 'Tumbangnya Tembok Berlin menandai runtuhnya tirai besi komunisme di Eropa Timur dan reunifikasi Jerman.',
  },
  {
    id: 31,
    q: 'Simbol palu dan arit pada lambang komunisme melambangkan persatuan antara?',
    opts: ['Buruh industri dan petani', 'Militer dan kaum cendekiawan', 'Pedagang dan pemilik modal', 'Birokrat dan agamawan'],
    correct: 0,
    why: 'Palu melambangkan kaum buruh pabrik perkotaan, dan arit melambangkan kaum petani pedesaan.',
  },
  {
    id: 32,
    q: 'Doktrin fasisme di Jerman yang menekankan perlunya ruang hidup (ekspansi wilayah) disebut?',
    opts: ['Lebensraum', 'Perestroika', 'Glasnost', 'Blitzkrieg'],
    correct: 0,
    why: 'Lebensraum adalah konsep geopolitik Nazi untuk mencaplok wilayah Eropa Timur demi kelangsungan ras Arya.',
  },

  // ==================== SOAL BARU — LIBERALISME (33-47) ====================
  {
    id: 33,
    q: "John Stuart Mill terkenal lewat karya 'On Liberty' yang membahas tentang?",
    opts: ['Kebebasan individu dan batasnya', 'Perjuangan kelas', 'Negara totaliter', 'Ekonomi komando'],
    correct: 0,
    why: "Mill membahas sejauh mana kebebasan individu boleh dibatasi, terutama lewat 'harm principle'.",
  },
  {
    id: 34,
    q: 'Montesquieu mencetuskan konsep pemisahan kekuasaan negara menjadi tiga cabang, yaitu?',
    opts: ['Militer, sipil, agama', 'Legislatif, eksekutif, yudikatif', 'Pusat, daerah, adat', 'Ekonomi, politik, budaya'],
    correct: 1,
    why: 'Trias politica Montesquieu memisahkan kekuasaan agar saling mengawasi dan tidak terpusat.',
  },
  {
    id: 35,
    q: 'Piagam yang membatasi kekuasaan mutlak Raja Inggris pada tahun 1215 dan menjadi cikal bakal konstitusionalisme adalah?',
    opts: ['Bill of Rights', 'Magna Carta', 'Declaration of Independence', 'Petition of Right'],
    correct: 1,
    why: 'Magna Carta (1215) untuk pertama kalinya menegaskan bahwa raja pun tunduk pada hukum.',
  },
  {
    id: 36,
    q: 'Revolusi Inggris tahun 1688 yang menggulingkan raja tanpa banyak pertumpahan darah dan melahirkan Bill of Rights 1689 disebut?',
    opts: ['Glorious Revolution', 'Revolusi Prancis', 'Revolusi Industri', 'Revolusi Puritan'],
    correct: 0,
    why: 'Glorious Revolution memperkuat kekuasaan parlemen atas raja dan menjadi tonggak liberalisme Inggris.',
  },
  {
    id: 37,
    q: 'Penulis utama naskah Deklarasi Kemerdekaan Amerika Serikat 1776 adalah?',
    opts: ['George Washington', 'Thomas Jefferson', 'Benjamin Franklin', 'Alexander Hamilton'],
    correct: 1,
    why: 'Thomas Jefferson menyusun naskah yang menekankan hak atas hidup, kebebasan, dan pengejaran kebahagiaan.',
  },
  {
    id: 38,
    q: "Konsep 'kontrak sosial' yang menyatakan kekuasaan pemerintah berasal dari persetujuan rakyat, salah satunya dikembangkan oleh?",
    opts: ['John Locke', 'Karl Marx', 'Benito Mussolini', 'Joseph Stalin'],
    correct: 0,
    why: 'Locke berpendapat pemerintah hanya sah jika mendapat persetujuan dari rakyat yang diperintah.',
  },
  {
    id: 39,
    q: "Ekonom pemikir neoliberalisme abad ke-20 yang menulis buku 'The Road to Serfdom' adalah?",
    opts: ['John Maynard Keynes', 'Friedrich Hayek', 'Karl Marx', 'Vladimir Lenin'],
    correct: 1,
    why: 'Hayek memperingatkan bahwa perencanaan ekonomi terpusat dapat mengarah pada tirani.',
  },
  {
    id: 40,
    q: 'Periode sejarah Indonesia 1950-1959 yang menerapkan sistem multipartai dan kabinet parlementer ala liberal dikenal sebagai era?',
    opts: ['Demokrasi Terpimpin', 'Demokrasi Liberal/Parlementer', 'Orde Baru', 'Reformasi'],
    correct: 1,
    why: 'Pada era ini Indonesia menganut sistem multipartai dengan pergantian kabinet yang sering terjadi.',
  },
  {
    id: 41,
    q: "Mekanisme 'checks and balances' dalam sistem liberal bertujuan untuk?",
    opts: ['Mempercepat pengambilan keputusan', 'Mencegah penyalahgunaan kekuasaan oleh satu lembaga', 'Menyatukan seluruh kekuasaan pada satu pemimpin', 'Menghapus lembaga yudikatif'],
    correct: 1,
    why: 'Saling mengawasi antarlembaga negara mencegah satu pihak menjadi terlalu berkuasa.',
  },
  {
    id: 42,
    q: "Prinsip hukum 'habeas corpus' berfungsi melindungi warga negara dari?",
    opts: ['Pajak yang tinggi', 'Penahanan sewenang-wenang tanpa proses hukum yang adil', 'Persaingan usaha', 'Sensor pers'],
    correct: 1,
    why: 'Habeas corpus mewajibkan otoritas menghadirkan tahanan ke pengadilan dan menjelaskan alasan penahanannya.',
  },
  {
    id: 43,
    q: "Filsuf abad ke-20 yang menulis 'A Theory of Justice' dan berpengaruh besar pada liberalisme politik modern adalah?",
    opts: ['John Rawls', 'Michel Foucault', 'Antonio Gramsci', 'Jean-Paul Sartre'],
    correct: 0,
    why: 'Rawls mengusulkan prinsip keadilan berbasis kesetaraan kesempatan dalam masyarakat liberal.',
  },
  {
    id: 44,
    q: 'Prinsip ekonomi liberal klasik yang menolak campur tangan negara dalam pasar disebut?',
    opts: ['Proteksionisme', 'Laissez-faire', 'Etatisme', 'Autarki'],
    correct: 1,
    why: 'Laissez-faire meyakini pasar akan mengatur dirinya sendiri secara efisien tanpa intervensi negara.',
  },
  {
    id: 45,
    q: 'Salah satu kritik umum terhadap liberalisme adalah kecenderungannya mengabaikan?',
    opts: ['Kebebasan pers', 'Kesenjangan ekonomi dan keadilan sosial kolektif', 'Hak pilih warga', 'Supremasi hukum'],
    correct: 1,
    why: 'Kritik liberalisme klasik sering menyoroti minimnya perhatian pada pemerataan ekonomi.',
  },
  {
    id: 46,
    q: 'Sistem multipartai yang memungkinkan berbagai kelompok politik bersaing secara bebas mencerminkan nilai liberal yang disebut?',
    opts: ['Pluralisme politik', 'Sentralisme demokratik', 'Totalitarianisme', 'Korporatisme'],
    correct: 0,
    why: 'Pluralisme politik menjamin keberagaman suara dan pilihan bagi warga negara.',
  },
  {
    id: 47,
    q: 'Liberalisme sosial (social liberalism) berbeda dari liberalisme klasik karena cenderung mendukung?',
    opts: ['Penghapusan pemilu', 'Peran negara dalam jaminan sosial/kesejahteraan warga', 'Kepemilikan kolektif penuh atas tanah', 'Kediktatoran satu partai'],
    correct: 1,
    why: 'Liberalisme sosial menerima peran negara lebih besar demi kesejahteraan tanpa meninggalkan kebebasan individu.',
  },

  // ==================== SOAL BARU — KOMUNISME (48-62) ====================
  {
    id: 48,
    q: 'Karya utama Karl Marx yang menganalisis kritik ekonomi kapitalisme secara mendalam berjudul?',
    opts: ['Das Kapital', 'The Wealth of Nations', 'On Liberty', 'Mein Kampf'],
    correct: 0,
    why: 'Das Kapital adalah analisis ekonomi-politik Marx tentang cara kerja dan kontradiksi sistem kapitalisme.',
  },
  {
    id: 49,
    q: "Konsep 'materialisme historis' dalam pemikiran Marx menjelaskan bahwa perkembangan sejarah manusia digerakkan terutama oleh?",
    opts: ['Agama', 'Kondisi dan hubungan ekonomi/produksi', 'Perang antarbangsa', 'Kehendak individu pemimpin'],
    correct: 1,
    why: 'Marx melihat struktur ekonomi sebagai fondasi yang membentuk seluruh aspek sosial dan politik.',
  },
  {
    id: 50,
    q: "Istilah 'diktator proletariat' dalam teori Marxis-Leninis merujuk pada?",
    opts: ['Pemerintahan kelas buruh sebagai tahap transisi menuju masyarakat tanpa kelas', 'Kediktatoran satu jenderal militer', 'Kekuasaan mutlak kaum borjuis', 'Sistem kerajaan turun-temurun'],
    correct: 0,
    why: 'Tahap ini dianggap perlu untuk menghapus sisa kekuatan borjuis sebelum tercapainya masyarakat komunis penuh.',
  },
  {
    id: 51,
    q: 'Kebijakan ekonomi Lenin yang untuk sementara mengizinkan sedikit unsur pasar bebas demi memulihkan ekonomi Uni Soviet awal 1920-an disebut?',
    opts: ['Kolektivisasi paksa', 'New Economic Policy (NEP)', 'Glasnost', 'Perestroika'],
    correct: 1,
    why: 'NEP diberlakukan Lenin sebagai kompromi sementara untuk memulihkan produksi setelah perang saudara Rusia.',
  },
  {
    id: 52,
    q: 'Program industrialisasi bertahap ala Uni Soviet di bawah Stalin yang terkenal disebut?',
    opts: ['Marshall Plan', 'Rencana Lima Tahun (Five-Year Plan)', 'New Deal', 'Great Society'],
    correct: 1,
    why: 'Rencana Lima Tahun mempercepat industrialisasi Uni Soviet lewat target produksi terpusat.',
  },
  {
    id: 53,
    q: 'Pemimpin Revolusi Kuba 1959 yang mendirikan negara komunis di Amerika Latin adalah?',
    opts: ['Che Guevara', 'Fidel Castro', 'Hugo Chavez', 'Salvador Allende'],
    correct: 1,
    why: 'Fidel Castro memimpin revolusi yang menggulingkan rezim Batista dan mendirikan negara sosialis Kuba.',
  },
  {
    id: 54,
    q: 'Ideologi resmi Korea Utara yang memadukan komunisme dengan penekanan kemandirian nasional disebut?',
    opts: ['Juche', 'Maoisme', 'Titoisme', 'Trotskyisme'],
    correct: 0,
    why: "Juche menekankan kemandirian (self-reliance) sebagai prinsip utama negara Korea Utara.",
  },
  {
    id: 55,
    q: 'Organisasi internasional yang dibentuk untuk mengoordinasikan partai-partai komunis di berbagai negara disebut?',
    opts: ['NATO', 'Komintern (Communist International)', 'Pakta Warsawa', 'SEATO'],
    correct: 1,
    why: 'Komintern didirikan untuk menyebarkan dan mengoordinasikan revolusi komunis dunia.',
  },
  {
    id: 56,
    q: 'Aliansi militer negara-negara blok komunis Eropa Timur selama Perang Dingin sebagai tandingan NATO disebut?',
    opts: ['Pakta Warsawa', 'Liga Bangsa-Bangsa', 'ASEAN', 'Blok Sekutu'],
    correct: 0,
    why: 'Pakta Warsawa dibentuk 1955 sebagai aliansi pertahanan bersama negara-negara komunis Eropa Timur.',
  },
  {
    id: 57,
    q: 'Kebijakan Mao Zedong di China akhir 1950-an yang bertujuan mempercepat industrialisasi lewat kolektivisasi pertanian secara drastis disebut?',
    opts: ['Revolusi Kebudayaan', 'Lompatan Jauh ke Depan (Great Leap Forward)', 'Kebijakan Pintu Terbuka', 'Reformasi Deng Xiaoping'],
    correct: 1,
    why: 'Kebijakan ini bertujuan mempercepat modernisasi China namun berujung pada bencana kelaparan besar.',
  },
  {
    id: 58,
    q: 'Simbol palu dan arit pada bendera komunis melambangkan persatuan antara?',
    opts: ['Buruh industri dan petani', 'Tentara dan ulama', 'Pedagang dan bangsawan', 'Ilmuwan dan seniman'],
    correct: 0,
    why: 'Palu mewakili buruh pabrik dan arit mewakili petani sebagai dua pilar utama revolusi sosialis.',
  },
  {
    id: 59,
    q: 'Partai berideologi komunis yang pernah aktif di Indonesia sebelum dibubarkan pasca peristiwa 1965 dikenal dengan singkatan?',
    opts: ['PNI', 'PKI', 'Masyumi', 'PSI'],
    correct: 1,
    why: 'PKI (Partai Komunis Indonesia) adalah partai berideologi komunis yang dibubarkan setelah peristiwa G30S 1965.',
  },
  {
    id: 60,
    q: 'Pemimpin Vietnam yang memimpin perjuangan kemerdekaan dan penyatuan Vietnam di bawah paham komunis adalah?',
    opts: ['Ho Chi Minh', 'Pol Pot', 'Sukarno', 'Norodom Sihanouk'],
    correct: 0,
    why: 'Ho Chi Minh memimpin gerakan komunis Vietnam melawan penjajahan Prancis dan kemudian Amerika Serikat.',
  },
  {
    id: 61,
    q: 'Salah satu ciri sistem ekonomi komunis dibanding kapitalis adalah tidak adanya?',
    opts: ['Sekolah', 'Kepemilikan pribadi atas alat produksi utama', 'Militer', 'Uang tunai sama sekali dalam segala bentuk'],
    correct: 1,
    why: 'Komunisme meniadakan kepemilikan pribadi atas alat produksi besar demi kepemilikan kolektif/negara.',
  },
  {
    id: 62,
    q: 'Tujuan akhir cita-cita komunisme menurut Marx adalah terciptanya masyarakat?',
    opts: ['Tanpa kelas dan tanpa negara', 'Monarki konstitusional', 'Federasi agama', 'Pasar bebas penuh'],
    correct: 0,
    why: 'Marx membayangkan tahap akhir sejarah sebagai masyarakat komunis yang egaliter tanpa kelas maupun aparatus negara.',
  },

  // ==================== SOAL BARU — FASISME (63-77) ====================
  {
    id: 63,
    q: "Istilah 'fasisme' berasal dari kata Italia 'fascio' yang secara harfiah berarti?",
    opts: ['Pedang', 'Ikatan/berkas batang kayu', 'Elang', 'Bendera'],
    correct: 1,
    why: "'Fascio' merujuk pada simbol Romawi kuno berupa berkas kayu yang diikat sebagai lambang kekuatan bersatu.",
  },
  {
    id: 64,
    q: 'Aksi politik Mussolini pada 1922 yang membawanya berkuasa di Italia disebut?',
    opts: ['March on Rome (Pawai ke Roma)', 'Kristallnacht', 'Enabling Act', 'Anschluss'],
    correct: 0,
    why: 'Pawai kaum fasis ke Roma memaksa Raja Victor Emmanuel III menunjuk Mussolini sebagai perdana menteri.',
  },
  {
    id: 65,
    q: 'Undang-undang yang memberi Hitler kekuasaan darurat luar biasa di Jerman tahun 1933 disebut?',
    opts: ['Nuremberg Laws', 'Enabling Act (Ermächtigungsgesetz)', 'Treaty of Versailles', 'Weimar Constitution'],
    correct: 1,
    why: 'Enabling Act memungkinkan Hitler membuat undang-undang tanpa persetujuan parlemen, membuka jalan ke kediktatoran.',
  },
  {
    id: 66,
    q: 'Proses penyeragaman seluruh institusi masyarakat Jerman di bawah kendali Partai Nazi disebut?',
    opts: ['Gleichschaltung', 'Blitzkrieg', 'Lebensraum', 'Perestroika'],
    correct: 0,
    why: 'Gleichschaltung menghapus pluralisme institusi agar semuanya tunduk pada garis Partai Nazi.',
  },
  {
    id: 67,
    q: "Konsep Nazi yang menuntut perluasan 'ruang hidup' bagi bangsa Jerman lewat penaklukan wilayah disebut?",
    opts: ['Lebensraum', 'Anschluss', 'Autarki', 'Volksgemeinschaft'],
    correct: 0,
    why: 'Lebensraum menjadi dasar pembenaran ekspansi militer Nazi ke Eropa Timur.',
  },
  {
    id: 68,
    q: 'Peristiwa penggabungan paksa Austria ke dalam Jerman Nazi pada 1938 disebut?',
    opts: ['Anschluss', 'Kristallnacht', 'Blitzkrieg', 'Putsch'],
    correct: 0,
    why: 'Anschluss adalah aneksasi Austria oleh Jerman Nazi tanpa perlawanan berarti.',
  },
  {
    id: 69,
    q: 'Diktator fasis Spanyol yang berkuasa sejak akhir Perang Saudara Spanyol (1939) hingga 1975 adalah?',
    opts: ['Francisco Franco', 'Benito Mussolini', 'Antonio Salazar', 'Miguel Primo de Rivera'],
    correct: 0,
    why: 'Franco memerintah Spanyol sebagai diktator otoriter selama hampir empat dekade.',
  },
  {
    id: 70,
    q: 'Model ekonomi yang diterapkan rezim fasis, di mana negara mengatur kerja sama paksa antara pengusaha dan buruh dalam satu wadah tunggal disebut?',
    opts: ['Korporatisme', 'Sosialisme pasar', 'Ekonomi komando penuh', 'Federalisme fiskal'],
    correct: 0,
    why: 'Korporatisme fasis menyatukan kepentingan buruh dan pengusaha di bawah kendali negara, meniadakan serikat independen.',
  },
  {
    id: 71,
    q: 'Organisasi paramiliter Nazi yang berperan sebagai pasukan keamanan rezim dan pelaksana kebijakan rasial dikenal sebagai?',
    opts: ['SS (Schutzstaffel)', 'NATO', 'Komintern', 'NKVD'],
    correct: 0,
    why: 'SS menjadi salah satu instrumen kekerasan dan represi utama rezim Nazi.',
  },
  {
    id: 72,
    q: 'Perjanjian yang dianggap mempermalukan Jerman pasca Perang Dunia I dan dimanfaatkan propaganda Nazi untuk membangkitkan nasionalisme balas dendam adalah?',
    opts: ['Perjanjian Versailles', 'Perjanjian Locarno', 'Pakta Molotov-Ribbentrop', 'Perjanjian München'],
    correct: 0,
    why: 'Perjanjian Versailles membebani Jerman dengan reparasi berat dan pembatasan militer, memicu kebencian nasionalis.',
  },
  {
    id: 73,
    q: 'Aliansi tiga kekuatan fasis/militeris utama pada Perang Dunia II (Jerman-Italia-Jepang) dikenal sebagai?',
    opts: ['Blok Sekutu', 'Poros (Axis Powers)', 'Blok Non-Blok', 'Entente'],
    correct: 1,
    why: 'Jerman, Italia, dan Jepang membentuk Blok Poros yang berperang melawan Blok Sekutu.',
  },
  {
    id: 74,
    q: 'Ciri fasisme yang menolak perdebatan/oposisi politik dan menuntut kepatuhan mutlak pada pemimpin tunggal disebut?',
    opts: ['Kultus pemimpin (leader cult)', 'Federalisme', 'Bikameralisme', 'Referendum rutin'],
    correct: 0,
    why: 'Fasisme memuja sosok pemimpin tunggal (Duce/Führer) sebagai personifikasi kehendak bangsa.',
  },
  {
    id: 75,
    q: 'Simbol yang diadopsi Partai Nazi sebagai lambang gerakannya adalah?',
    opts: ['Bintang merah', 'Swastika', 'Palu arit', 'Elang berkepala dua'],
    correct: 1,
    why: 'Swastika menjadi lambang resmi Partai Nazi dan negara Jerman di era Reich Ketiga.',
  },
  {
    id: 76,
    q: 'Fasisme umumnya ditempatkan pada spektrum politik mana oleh para ilmuwan politik?',
    opts: ['Kiri jauh (far-left)', 'Kanan jauh (far-right) / ultranasionalis', 'Tengah/moderat', 'Anarkis'],
    correct: 1,
    why: 'Penekanan pada hierarki, nasionalisme ekstrem, dan penolakan kesetaraan kelas menempatkan fasisme di kanan jauh.',
  },
  {
    id: 77,
    q: 'Salah satu alasan fasisme menolak komunisme secara ideologis adalah karena komunisme menekankan?',
    opts: ['Perjuangan kelas internasional, bukan persatuan bangsa tunggal', 'Kebebasan pasar', 'Demokrasi liberal', 'Federalisme'],
    correct: 0,
    why: 'Fasisme menganggap solidaritas kelas lintas negara ala komunisme mengancam persatuan nasional yang mereka agungkan.',
  },

  // ==================== SOAL BARU — KAPITALISME (78-92) ====================
  {
    id: 78,
    q: 'Perusahaan dagang seperti VOC (Belanda) dan East India Company (Inggris) pada abad ke-17 sering dianggap sebagai bentuk awal dari?',
    opts: ['Sosialisme negara', 'Kapitalisme merkantilis/korporasi awal', 'Komunisme primitif', 'Fasisme kolonial'],
    correct: 1,
    why: 'Perusahaan-perusahaan dagang ini mengumpulkan modal dari investor swasta untuk mencari keuntungan, cikal bakal korporasi modern.',
  },
  {
    id: 79,
    q: "Konsep 'keunggulan komparatif' dalam perdagangan bebas antarnegara dikemukakan oleh ekonom?",
    opts: ['David Ricardo', 'Karl Marx', 'Vladimir Lenin', 'Benito Mussolini'],
    correct: 0,
    why: 'Ricardo menjelaskan bahwa negara sebaiknya fokus memproduksi barang yang paling efisien mereka hasilkan lalu berdagang.',
  },
  {
    id: 80,
    q: 'Krisis ekonomi global yang dipicu jatuhnya pasar saham Wall Street pada tahun 1929 dikenal sebagai awal dari?',
    opts: ['Perang Dingin', 'Depresi Besar (Great Depression)', 'Revolusi Industri', 'Krisis Minyak'],
    correct: 1,
    why: 'Depresi Besar menyebabkan pengangguran massal dan keruntuhan ekonomi di banyak negara kapitalis pada 1930-an.',
  },
  {
    id: 81,
    q: 'Ekonom yang gagasannya (intervensi negara untuk menstabilkan ekonomi lewat belanja publik) menjadi respons utama terhadap Depresi Besar adalah?',
    opts: ['John Maynard Keynes', 'Friedrich Hayek', 'Adam Smith', 'Milton Friedman'],
    correct: 0,
    why: 'Keynes berargumen negara perlu aktif mengintervensi ekonomi saat pasar gagal pulih dengan sendirinya.',
  },
  {
    id: 82,
    q: 'Kebijakan Presiden AS Franklin D. Roosevelt untuk memulihkan ekonomi pasca Depresi Besar lewat proyek publik dan regulasi dikenal sebagai?',
    opts: ['New Deal', 'Great Society', 'Marshall Plan', 'Reaganomics'],
    correct: 0,
    why: 'New Deal menghadirkan program kerja publik dan regulasi keuangan untuk memulihkan ekonomi AS.',
  },
  {
    id: 83,
    q: 'Istilah untuk perusahaan yang beroperasi dan memiliki aset produksi di banyak negara sekaligus, ciri khas kapitalisme global modern, disebut?',
    opts: ['Koperasi lintas negara', 'Perusahaan multinasional (MNC)', 'BUMN internasional', 'Kolektif buruh dunia'],
    correct: 1,
    why: 'Perusahaan multinasional memperluas jangkauan modal dan produksi kapitalis ke seluruh dunia.',
  },
  {
    id: 84,
    q: 'Ekonom monetaris abad ke-20 yang menekankan pentingnya kebijakan moneter dibanding intervensi fiskal negara adalah?',
    opts: ['Milton Friedman', 'Karl Marx', 'John Locke', 'Friedrich Engels'],
    correct: 0,
    why: 'Friedman meyakini pengendalian jumlah uang beredar lebih efektif menstabilkan ekonomi dibanding belanja pemerintah.',
  },
  {
    id: 85,
    q: 'Istilah Marx untuk menggambarkan perasaan buruh yang terasing dari hasil kerjanya sendiri dalam sistem kapitalis disebut?',
    opts: ['Alienasi', 'Nasionalisme', 'Kolektivisasi', 'Korporatisme'],
    correct: 0,
    why: 'Marx menyebut buruh mengalami alienasi karena tidak lagi memiliki kendali atau ikatan atas hasil kerjanya.',
  },
  {
    id: 86,
    q: 'Sistem ekonomi campuran di mana negara tetap memainkan peran besar dalam mengatur pasar (bukan laissez-faire murni) sering disebut?',
    opts: ['Ekonomi komando penuh', 'Kapitalisme negara/ekonomi campuran', 'Feodalisme', 'Barter murni'],
    correct: 1,
    why: 'Banyak negara kapitalis modern mengombinasikan pasar bebas dengan regulasi dan jaminan sosial negara.',
  },
  {
    id: 87,
    q: "Istilah 'kroniisme' (crony capitalism) merujuk pada praktik kapitalisme yang menyimpang karena?",
    opts: ['Kedekatan pengusaha dengan pejabat memberi keuntungan tidak adil', 'Persaingan pasar yang terlalu ketat', 'Kepemilikan negara penuh atas industri', 'Tidak adanya uang dalam sistem ekonomi'],
    correct: 0,
    why: 'Crony capitalism terjadi ketika keberhasilan usaha lebih ditentukan oleh koneksi politik ketimbang persaingan sehat.',
  },
  {
    id: 88,
    q: 'Bursa saham yang menjadi pusat utama kapitalisme finansial dunia dan berlokasi di New York disebut?',
    opts: ['Wall Street (NYSE)', 'Nikkei', 'Bursa Efek Indonesia', 'FTSE London'],
    correct: 0,
    why: 'Wall Street/New York Stock Exchange menjadi simbol pusat keuangan dan modal kapitalisme global.',
  },
  {
    id: 89,
    q: "Konsep 'standar emas' (gold standard) dalam sejarah kapitalisme berfungsi sebagai?",
    opts: ['Dasar nilai tukar mata uang yang diikat pada cadangan emas', 'Sistem barter langsung', 'Pajak atas barang impor', 'Alat propaganda politik'],
    correct: 0,
    why: 'Standar emas mengaitkan nilai mata uang suatu negara dengan cadangan emas yang dimilikinya.',
  },
  {
    id: 90,
    q: 'Fenomena ekonomi global akhir abad ke-20 yang mempercepat aliran modal, barang, dan tenaga kerja antarnegara, erat kaitannya dengan ekspansi kapitalisme, disebut?',
    opts: ['Globalisasi', 'Isolasionisme', 'Autarki', 'Proteksionisme total'],
    correct: 0,
    why: 'Globalisasi mempercepat integrasi pasar dan produksi kapitalis lintas batas negara.',
  },
  {
    id: 91,
    q: 'Model ekonomi hybrid China modern yang menggabungkan kontrol politik satu partai komunis dengan mekanisme pasar bebas sering disebut?',
    opts: ['Sosialisme pasar / kapitalisme negara ala China', 'Fasisme ekonomi', 'Liberalisme murni', 'Feodalisme modern'],
    correct: 0,
    why: 'China mengombinasikan kendali politik Partai Komunis dengan mekanisme pasar untuk mendorong pertumbuhan ekonomi.',
  },
  {
    id: 92,
    q: 'Salah satu argumen utama pembela kapitalisme adalah sistem ini dianggap paling efisien dalam?',
    opts: ['Mengalokasikan sumber daya lewat mekanisme harga dan persaingan', 'Menghapus seluruh kesenjangan sosial', 'Menjamin kepemilikan bersama', 'Menghilangkan kebutuhan akan uang'],
    correct: 0,
    why: 'Pembela kapitalisme meyakini harga pasar dan kompetisi mendorong efisiensi produksi dan inovasi.',
  },

  // ==================== SOAL BARU — PERBANDINGAN ANTAR-IDEOLOGI (93-99) ====================
  {
    id: 93,
    q: 'Ideologi manakah yang secara historis pernah menjadi sekutu sesama Blok Sekutu melawan fasisme pada Perang Dunia II meski secara ideologi saling bertentangan?',
    opts: ['Liberalisme (AS/Inggris) dan Komunisme (Uni Soviet)', 'Fasisme dan Kapitalisme', 'Komunisme dan Fasisme', 'Liberalisme dan Fasisme'],
    correct: 0,
    why: 'Demi mengalahkan Blok Poros, negara-negara liberal-kapitalis dan Uni Soviet komunis bersekutu sementara pada PD II.',
  },
  {
    id: 94,
    q: 'Dari keempat ideologi (Liberalisme, Komunisme, Fasisme, Kapitalisme), manakah yang paling menekankan penghapusan kelas sosial sebagai tujuan akhir?',
    opts: ['Liberalisme', 'Komunisme', 'Fasisme', 'Kapitalisme'],
    correct: 1,
    why: 'Komunisme mencita-citakan masyarakat tanpa kelas sebagai tahap akhir sejarah manusia.',
  },
  {
    id: 95,
    q: 'Ideologi mana yang secara ekonomi paling dekat/beririsan dengan kapitalisme, meski secara penekanan politiknya berbeda?',
    opts: ['Liberalisme', 'Fasisme', 'Komunisme', 'Semua sama jauhnya'],
    correct: 0,
    why: 'Liberalisme klasik dan kapitalisme sama-sama menjunjung tinggi kebebasan pasar dan hak milik pribadi.',
  },
  {
    id: 96,
    q: 'Sistem partai yang umum dijumpai pada negara berideologi fasis maupun komunis totaliter adalah?',
    opts: ['Sistem satu partai dominan/tunggal', 'Sistem multipartai penuh', 'Tanpa partai sama sekali', 'Partai berbasis agama saja'],
    correct: 0,
    why: 'Baik rezim fasis maupun komunis totaliter cenderung melarang oposisi dan hanya mengizinkan satu partai berkuasa.',
  },
  {
    id: 97,
    q: "Ideologi mana yang mengklaim menawarkan 'jalan ketiga' antara kapitalisme dan komunisme, berbasis negara-bangsa dan korporatisme?",
    opts: ['Liberalisme', 'Fasisme', 'Sosial demokrasi', 'Anarkisme'],
    correct: 1,
    why: 'Fasisme memposisikan diri menolak individualisme kapitalis maupun internasionalisme kelas komunis, dengan negara-bangsa sebagai pusatnya.',
  },
  {
    id: 98,
    q: 'Perang Dingin dapat dilihat sebagai pertarungan sistem ekonomi antara kapitalisme (Blok Barat) melawan?',
    opts: ['Fasisme (Blok Poros)', 'Komunisme/ekonomi komando (Blok Timur)', 'Feodalisme', 'Merkantilisme kolonial'],
    correct: 1,
    why: 'Perang Dingin mempertentangkan ekonomi pasar bebas Blok Barat dengan ekonomi terencana Blok Timur.',
  },
  {
    id: 99,
    q: 'Keempat ideologi dunia ini (Liberalisme, Komunisme, Fasisme, Kapitalisme) umumnya lahir atau berkembang pesat sebagai respons besar-besaran terhadap perubahan sosial-ekonomi akibat?',
    opts: ['Revolusi Industri dan modernisasi Eropa abad 18-20', 'Penemuan benua Amerika', 'Perang Salib', 'Zaman Batu'],
    correct: 0,
    why: 'Industrialisasi, urbanisasi, dan pergolakan sosial abad 18-20 menjadi lahan subur bagi lahirnya keempat ideologi besar ini.',
  },
];

export function getRandomQuestion(usedIds: number[] = []): Question {
  const available = QUESTIONS.filter((q) => !usedIds.includes(q.id));
  if (available.length === 0) {
    // Reset pool when all questions have been used
    const randomIndex = Math.floor(Math.random() * QUESTIONS.length);
    return QUESTIONS[randomIndex];
  }
  const randomIndex = Math.floor(Math.random() * available.length);
  return available[randomIndex];
}
